### ISSUE TITLE
🐛 `collection-submission-mailer` error

### ISSUE THREAD

**Issue by chartgerink** [libscie/ResearchEquals.com#1017]
### What happened?

Seems like the collection submission mailer crashed the site for a few seconds. Got a 503 after submitting a DOI.

### Anything else?

This is the error from runtime logs

```
Received job to api/collection-submission-mailer 39

/var/www/app/node_modules/postmark/dist/client/errors/Errors.js:124

return new ApiInputError(message, code, statusCode);
                
ApiInputError: The Template's 'Alias' associated with this request is not valid or was not found.
```

**Comment by chartgerink** [comment]
This is fixed now - the template had not been ported over regrettably from the test environment into the production environment, which meant it did not work...

Adding it to the playbook!

**Comment by nsunami** [comment]
Ah, the Postmark template! Makes sense!
