### ISSUE TITLE
Settings form field resizing

### ISSUE THREAD

**Issue by psobrakseaton** [libscie/ResearchEquals.com#102]
Browser: Safari

When I click on the settings wheel in the upper right corner, the “Profile URL” form field resizes causing a subtle, but annoying shift in the window. I have attached a screen recording...

https://user-images.githubusercontent.com/28573875/143842991-873546c9-de3b-49b5-87fd-8b5953086e60.mov

**Comment by chartgerink** [comment]
Can reproduce this in Safari - will check it out 😊

**Comment by chartgerink** [comment]
Fixed!
