### ISSUE TITLE
Verification email goes to “404”

### ISSUE THREAD

**Issue by psobrakseaton** [libscie/ResearchEquals.com#103]
When I click on the “Verify email” button in the verification email, it goes to a “404” page and doesn’t verify my email address. I found that by removing one of /’s between the “herokuapp.com” and “verifyEmail” in the URL “https://researchequals-staging.herokuapp.com//verifyEmail/JGFyZ29…” I was able to successfully verify the email address.
<img width="591" alt="Screen Shot 2021-11-29 at 10 35 36" src="https://user-images.githubusercontent.com/28573875/143843139-0f9c1c8b-1713-498d-a96f-b3aad8278495.png">

**Comment by chartgerink** [comment]
Same issue as #96 --- fixed!

> The issue here was not in the code, but in the environment variables on the server 😅 `APP_ORIGIN` was defined as `https://researchequals-staging.herokuapp.com/` --- the trailing slash had to be removed. This is already the case on the production server.
