### ISSUE TITLE
When editing a draft, the form stays populated

### ISSUE THREAD

**Issue by psobrakseaton** [libscie/ResearchEquals.com#112]
When editing a draft, the form stays populated with unsaved changes when you click the cancel editing icon the changes I made are still in the form despite me not saving anything. Perhaps this is intentional?

https://user-images.githubusercontent.com/28573875/144205023-f1623a46-34ff-4872-840c-68740c13c099.mov

**Comment by chartgerink** [comment]
It's an artefact right now - what do you think makes more sense?

1. Store changes temporarily so people can come back to them (reload will reset)
2. Reset upon closing the edit mode and lose the edits.

I am not sure which one I'd prefer 💭

**Comment by psobrakseaton** [comment]
> It's an artefact right now - what do you think makes more sense?
> 
> 1. Store changes temporarily so people can come back to them (reload will reset)
> 2. Reset upon closing the edit mode and lose the edits.
> 
> I am not sure which one I'd prefer 💭

I was thinking about this too. I think the conventional pattern would be to ask for a confirmation upon closing/canceling, similar to what the browser does to keep you from losing your place in a form. I understand this type of verification adds some development time, so perhaps for now it is best to store the changes temporarily.

This is something we should definitely try to fix soon however.

**Comment by chartgerink** [comment]
Would this reasoning also apply when switching to a different module? 

If so, that would complicate state management on the dev end. It's not impossible, but it seems like a potential day spent on a marginal UX improvement in this stage.

What do you think is the good route here?

**Comment by chartgerink** [comment]
It now does the exact opposite. Closing this issue as a result.
