### ISSUE TITLE
Deleting all drafts leaves strange empty state

### ISSUE THREAD

**Issue by psobrakseaton** [libscie/ResearchEquals.com#118]
Instead of returning to the previous empty state, when you delete all of your drafts, the architecture for the screen appears as though drafts could be there.
<img width="1743" alt="Screen Shot 2021-12-01 at 09 53 12" src="https://user-images.githubusercontent.com/28573875/144205530-e6d5c49d-2d21-4e1b-96ac-2725411d5d41.png">

**Comment by chartgerink** [comment]
Did you have something like this in mind?

![lg123](https://user-images.githubusercontent.com/2946344/144249374-4e93f6c0-e0ae-4c24-9a51-711db5cfa423.png)

**Comment by psobrakseaton** [comment]
Yup! This is exactly what I had in mind. I think encouraging the user to create a new draft is important here.
