### ISSUE TITLE
Feature request: add ResearchEquals to log in page

### ISSUE THREAD

**Issue by nuest** [libscie/ResearchEquals.com#1187]
The current title of the login page is "Log in". It might be me not using a tool correctly, but my password manager can not perfectly match the form because there are other websites that use the same page title.

Something like "Log in | ResearchEquals" would allow a perfect match and improve my login experience :smile:

**Comment by nsunami** [comment]
@nuest In PR #1189, I assumed that changing the title to "R= Log In" would solve your issue. If not, please let me know here.
