### ISSUE TITLE
Avatar changed to “file not found”

### ISSUE THREAD

**Issue by psobrakseaton** [libscie/ResearchEquals.com#122]
When I reopened the upload modal, to finish taking my picture, I was unable to click done and have the image upload. Upon refreshing the page, my avatar shows “file not found”.
<img width="1743" alt="Screen Shot 2021-12-01 at 09 48 45" src="https://user-images.githubusercontent.com/28573875/144205690-bd757d5a-bfbc-43e7-ba2a-bc6c86bbd53d.png">

**Comment by chartgerink** [comment]
I cannot reproduce this - it also seems like your avatar loaded afterwards? 

Is there any additional information that may help reproduce this issue - anything you did that specific instance? It may have been a delay in Uploadcare's CDN.

**Comment by psobrakseaton** [comment]
I am attempt to recreate this myself, but sadly I can't think of any more information that could help reproduce this except for the fact that I was using Safari.

**Comment by chartgerink** [comment]
This has not occurred anymore and resolved itself. Going to close this issue, and if it pops up again please feel invited to open another issue! 😊
