### ISSUE TITLE
Settings modal changing sizes with each tab

### ISSUE THREAD

**Issue by psobrakseaton** [libscie/ResearchEquals.com#125]
When clicking on each tab of the settings modal (Workspace, Account, Billing) the modal resizes itself based on the content and the empty tab (billing) shrinks the whole modal down completely.
<img width="1743" alt="Screen Shot 2021-12-01 at 09 40 49" src="https://user-images.githubusercontent.com/28573875/144205851-e6494614-57a1-4e9b-a045-3d27cf340aa2.png">
<img width="1743" alt="Screen Shot 2021-12-01 at 09 40 53" src="https://user-images.githubusercontent.com/28573875/144205863-708bfe70-2a8c-4223-9b63-526ece49a5f4.png">
<img width="1743" alt="Screen Shot 2021-12-01 at 09 40 59" src="https://user-images.githubusercontent.com/28573875/144205874-96ce43f3-3570-436c-bd33-c712bc9aea57.png">

**Comment by chartgerink** [comment]
@psobrakseaton do you still consider this an issue in the current implementation?

**Comment by chartgerink** [comment]
Closing for staleness.
