### ISSUE TITLE
Persistent loading icon on home screen

### ISSUE THREAD

**Issue by psobrakseaton** [libscie/ResearchEquals.com#128]
My header section containing my settings gear, account name, create button etc. was not loading properly and just displayed a loading icon.
<img width="1904" alt="Screen Shot 2021-12-01 at 09 33 40" src="https://user-images.githubusercontent.com/28573875/144206021-55e7fc8a-b380-459e-ab15-6a1be763e963.png">

**Comment by chartgerink** [comment]
Ah yes! Sorry for the hassle.

For security purposes, any information that requires either private data to be sent or retrieved from the server is not loaded when the website is visited from `http://` (unsecured connection). This will result in a neverending loading animation. Firefox and Chrome default to `https://` - Safari does not.

Please double check that the link starts `https://` (secured connection) - this should resolve that issue.
