### ISSUE TITLE
`tsx` breaks upon upgrade to `3.14.0`

### ISSUE THREAD

**Issue by chartgerink** [libscie/ResearchEquals.com#1738]
The `tsx` library has some breaking change for us upon upgrading from `3.13.0` to `3.14.0`. This was unexpected as the changelog does not mention any 
specific issues in the upgrade for this minor version. 

## Error

```
chjh@module ResearchEquals.com % npm run test:xml

> researchequals@1.0.0 test:xml
> tsx app/core/crossref/rawtest.ts

TypeError: Cannot destructure property 'port' of 'undefined' as it is undefined.
    at z (file:///Users/chjh/git/libscie/ResearchEquals.com/node_modules/tsx/dist/esm/index.mjs:2:106)
    at ESMLoader.preload (node:internal/modules/esm/loader:362:48)
    at ESMLoader.addCustomLoaders (node:internal/modules/esm/loader:194:10)
    at initializeLoader (node:internal/process/esm_loader:82:19)
    at async loadESM (node:internal/process/esm_loader:87:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)
```

## Debug

I specifically tested with previous versions up to `3.13.0` - all work until it upgrades to `3.14.0`. [The `tsx` 
changelog](https://github.com/esbuild-kit/tsx/releases/tag/v3.14.0) is rather sparse on details. 

## Help

@tefkah - do you have any idea what this error may be in relation to? My VS Code instance does not indicate any type errors in the 
`app/core/crossref/rawtest.ts` file, and I am having trouble finding the issue here.

**Comment by tefkah** [comment]
huh, weird.
I just tested it locally and did not run into any problem, what node version are you using? I was running 18.15

**Comment by chartgerink** [comment]
I was using node@16.x when I had this issue. I since then upgrade to 18.x and indeed the issue no longer exists.

Sorry for the apparently unnecessary ping @tefkah - thanks for responding 😊
