### ISSUE TITLE
Add social image metadata

### ISSUE THREAD

**Issue by chartgerink** [libscie/ResearchEquals.com#1747]
After removing our `og-images` app, we now need new social sharing images. It is at this point unclear, so we are open to suggestions. 

Probably, we will stick with static ones for now, given that using `puppeteer` proved to be more resource intensive even though we could create custom ones 
for each. Using something like Bannerbear is too expensive at this point (starts at 500USD a month last I checked..).

**Comment by nsunami** [comment]
Would something like this Vercel OG Image Generation an option? 
https://vercel.com/blog/introducing-vercel-og-image-generation-fast-dynamic-social-card-images

**Comment by chartgerink** [comment]
Thanks @nsunami! I didn't know about this one, but it seems like a viable option indeed. It seems like this would be more reliable too, which was the main issue we previously had (too high load times).

We still have the original code that we've previously used, so if anybody wants to try their hand at this:
https://github.com/libscie/og-images/blob/main/index.js

**Comment by chartgerink** [comment]
Closing this issue as it's gone stale. Noting it for our current evaluation nonetheless.
