### ISSUE TITLE
Using an email with an addendum causes problems in the payment portal

### ISSUE THREAD

**Issue by psobrakseaton** [libscie/ResearchEquals.com#182]
Apologies, accidentally submitted before finishing the description...

Anyways, I tried signing up for researchequals.com using that classic gmail trick of using "+" in your email to differentiate it in your account. I used "patch+requals@libsice.org". Signup and verification went well, but when I tested paying for a module, I got this error:

![https___researchequals-staging herokuapp com_api_checkout_sessions_email=patch+requals@libscie org price_id=price_1KCRbjLmgtJbKHNGLa8TS0aH suffix=tez0-y7q7 module_id=13 - Google Chrome 03_01_2022 14_57_52](https://user-images.githubusercontent.com/28573875/147939331-c4bae5b1-3089-4101-849a-f93d920d1790.png)

This occurred just after clicking "Pay and publish"...

**Comment by chartgerink** [comment]
Thanks for reporting! Important bug 🐞

I expect the issue to lie with how the email is parsed as a parameter in the link, and that should be easy to fix. I will fix it 📘
