### ISSUE TITLE
Visual bug Collections modal🐛 

### ISSUE THREAD

**Issue by chartgerink** [libscie/ResearchEquals.com#1986]
### What happened?

<img width="978" alt="Screenshot 2024-03-01 at 10 26 13" src="https://github.com/libscie/ResearchEquals.com/assets/2946344/352737e9-4f4a-4680-b295-caca1336b1cf">

### What browser(s) did you use?

Firefox

**Comment by nsunami** [comment]
@chartgerink Ok if I pick this up?

**Comment by nsunami** [comment]
I was able to replicate this issue when the screen width is 1535px or wider.
