### ISSUE TITLE
Cohesive icons

### ISSUE THREAD

**Issue by psobrakseaton** [libscie/ResearchEquals.com#200]
I was looking into alternatives to the mix of Carbon and Hero that we are using at the moment, however, I couldn't find anything with the breadth of content and good construction of Carbon, so I went all in on it. 

It is worth noting that I am linking all Carbon Icons in their <IconName32 /> state. I am not doing any resizing here, I will do that in further design tweak GH issues. Implement them in the sizes sizes as they are right now in the app.

For the sake of completeness, I listed all the icons to the best of my knowledge currently in the app and Figma. I tried to verify which were Carbon already and which were not, but in the end I thought it best to list them all.

All icons that have yet to be implemented will use Carbon from here on out...

| Location               | Icon                                                            | Carbon Reference      |
| ---------------------- | ---------------------- | --------------------- |
| Signup                 | Check/Accept                                                    | `<Checkmark32 />`       |
| Signup                 | X/Cancel                                                        | `<Close32 />`           |
| \-                     | \-                                                              | \-                    |
| Settings               | Check/Save                                                      | `<Checkmark32 />`       |
| Settings               | X/Cancel                                                        | `<Close32 />`           |
| Settings               | Refresh ORCID                                                   | `<Renew32 />`           |
| Settings               | Delete/Trash can                                                | `<TrashCan32 />`        |
| \-                     | \-                                                              | \-                    |
| Dashboard              | OB - Verify                                                     | `<SendAlt32 />`         |
| Dashboard              | OB - Orcid                                                      | None - Use current    |
| Dashboard              | OB - Avatar                                                     | `<UserAvatar32 />`      |
| Dashboard              | OB - Info                                                       | `<Catalog32 />`         |
| \-                     | \-                                                              | \-                    |
| Header                 | Notification bell                                               | `<Notification32 />`    |
| Header                 | Notification bell - New                                         | `<NotificationNew32 />` |
| Header                 | Setting gear                                                    | `<Settings32 />`        |
| Header                 | Search/magnifying glass                                         | `<Search32 />`          |
| Header                 | Quick Draft - Plus                                              | `<Add32 />`             |
| Header - Mobile        | Hamburger                                                       | `<Menu32 />`            |
| Header - Mobile        | X/Close                                                         | `<Close32 />`           |
| \-                     | \-                                                              | \-                    |
| Feed - Desktop         | Chevron left                                                    | `<ChevronLeft32 />`     |
| Feed - Desktop         | Chevron right                                                   | `<ChevronRight32 />`    |
| \-                     | \-                                                              | \-                    |
| Handle                 | Date                                                            | `<Calendar32 />`        |
| Handle                 | Following                                                       | `<UserFollow32 />`      |
| Handle                 | Orcid                                                           | None - Use current    |
| Handle                 | Link                                                            | `<Link32 />`            |
| \-                     | \-                                                              | \-                    |
| Module\[id\]           | Maximize                                                        | `<Maximize32 />`        |
| Module\[id\] - Desktop | Minimize                                                        | `<Minimize32 />`        |
| Module\[id\] - Mobile  | Back arrow                                                      | `<ArrowLeft32 />`       |
| Module\[id\]           | Share                                                           | `<Share32 />`           |
| Module\[id\]           | PDF                                                             | `<DocumentPdf32 />`     |
| Module\[id\]           | Download                                                        | `<Download32 />`        |
| \-                     | \-                                                              | \-                    |
| Drafts                 | Edit                                                            | `<Edit32 />`            |
| Drafts                 | Maximize                                                        | `<Maximize32 />`        |
| Drafts - Desktop       | Minimize                                                        | `<Minimize32 />`        |
| Drafts - Mobile        | Back arrow                                                      | `<ArrowLeft32 />`       |
| Drafts                 | Search/magnifying glass                                         | `<Search32 />`          |
| Drafts                 | Download                                                        | `<Download32 />`        |
| Drafts                 | Delete/Trash                                                    | `<TrashCan32 />`        |
| Drafts                 | Plus - “Add Authors”, “Add Main File”, “Add Supporting File(s)” | `<Add32 />`             |
| Drafts                 | Authorship request                                              | `<UserFollow32 />`      |
| \-                     | \-                                                              | \-                    |
| Quick Draft            | Check/Save                                                      | `<Checkmark32 />`       |
| Quick Draft            | X/Close                                                         | `<Close32 />`           |
| Quick Draft            | X/Cancel                                                        | `<Close32 />`           |

**Comment by psobrakseaton** [comment]
I know this is a lot of checkboxes...If you want this formatted some other way, please let me know.

**Comment by psobrakseaton** [comment]
Here are a list of specific changes within the app:

### Signup
- [ ] Check/Accept - `<Checkmark32 />`
- [ ] X/Cancel -  `<Close32 />`

### Header - Desktop
- [ ] Notification - `<Notification32 />`
- [ ] New Notification - `<NotificationNew32 />`
- [ ] Settings gear - `<Settings32 />`
- [ ] Search - `<Search32 />`
- [ ] Quick Draft Button - `<Add32 />`

**Comment by psobrakseaton** [comment]
I understand that that leaves a lot for you to sort, so here's a list of specific changes in-app as I found them:

### Signup
- [ ] Check/Accept - `<Checkmark32 />`
- [ ] X/Cancel -  `<Close32 />`

### Header - Desktop
- [ ] Notification - `<Notification32 />`
- [ ] New Notification - `<NotificationNew32 />`
- [ ] Settings gear - `<Settings32 />`
- [ ] Search - `<Search32 />`
- [ ] Quick Draft Button - `<Add32 />`

### Header - Mobile
- [ ] Hamburger Menu - `<Menu32 />`
- [ ] X/Close - `<Close32 />`

### Feed - Desktop
- [ ] Chevron left - `<ChevronLeft32 />`
- [ ] Chevron right - `<ChevronRight32 />`

### Handle
- [ ] Date - `<Calendar32 />`
- [ ] Following - `<UserFollow32 />`
- [ ] ORCID - Current implementation
- [ ] Link - `<Link32 />`

### Quick Draft
- [ ] Check/Save - `<Checkmark32 />`
- [ ] X/Close - `<Close32 />`
- [ ] X/Cancel - `<Close32 />`

### Drafts - Desktop/General
- [ ] Plus Button ("Add Authors", "Add Main File", "Add Supporting File(s)") - `<Add32 />`
- [ ] Authorship request alert - `<UserFollow32 />`

**Comment by chartgerink** [comment]
There are a few pieces missing here, so keeping track below.

## Onboarding

- [ ] Onboarding email verification
- [ ] Onboarding avatar
- [ ] Onboarding profile info
- [ ] Onboarding first draft
