### ISSUE TITLE
🐛 issue with login and email verification

### ISSUE THREAD

**Issue by McHaillet** [libscie/ResearchEquals.com#2101]
### URL of the Page

https://researchequals.com/dashboard

### What happened?

When I login to researchequals, I get the following screen:

![image](https://github.com/libscie/ResearchEquals.com/assets/58044494/fe3f6c31-88fe-4cd9-9de2-2d62350b316c)

After I refresh the page, I am logged in and get the expected dashboard.

Additionally, the email verification is not working. After I click the link in my email, it hangs on the following screen:

![image](https://github.com/libscie/ResearchEquals.com/assets/58044494/a02bca1e-7501-41c9-963f-d043b85bf421)

The issues could very well be related.

### Steps to reproduce

I made a new account, only changed my first and last name in my profile.

### What browser(s) did you use?

Firefox

### Anything else?

I selected firefox as the browser as I tried that right now. However, earlier today I had the same issue on Chrome.

Let me know if you need more info!

**Comment by chartgerink** [comment]
Welcome and thanks @McHaillet 🙏 

On the email verification, it is a known issue that it can hang and as we're working towards our v2, this is unlikely to get fixed. Nonetheless, I checked and your email is verified despite this issue. 😊 

Regarding the log in error, I am not sure what is happening. I am unable to reproduce it at this time, even with a new account. Do you have any plugins installed in both Chrome and Firefox? Sometimes they can interfere, although I expect it is more likely an issue on our end 😅

**Comment by McHaillet** [comment]
Hi @chartgerink!

> On the email verification, it is a known issue that it can hang and as we're working towards our v2, this is unlikely to get fixed. Nonetheless, I checked and your email is verified despite this issue. 😊

Okay, that is good to know :+1: 

> Regarding the log in error, I am not sure what is happening. I am unable to reproduce it at this time, even with a new account. Do you have any plugins installed in both Chrome and Firefox? Sometimes they can interfere, although I expect it is more likely an issue on our end 😅

On firefox its only an adblocker extension. On Chrome I would need to check later today.

**Comment by chartgerink** [comment]
I suspect it isn't the problem then - thanks for letting me know! I will try to see whether I can reproduce. It'll be hard to fix if I can't 🤔 @nsunami have you encountered this issue?

**Comment by nsunami** [comment]
I tried logging in and out several times, and I got 400 once in those times (on production).

<img width="550" alt="image" src="https://github.com/libscie/ResearchEquals.com/assets/17035406/90304a5b-6d36-4af4-b4d4-a098c8ce56da">

But then, the error message is not "d is null" as first reported.

I'm going to take a look further now.

Meanwhile: @chartgerink: do you have any idea what "d is null" may mean / may be coming from?

**Comment by chartgerink** [comment]
It was fixed in #2103, this issue was not linked and not closed. Pardon the delay in reporting back on this!
