### ISSUE TITLE
Relational Icons

### ISSUE THREAD

**Issue by psobrakseaton** [libscie/ResearchEquals.com#220]
The relational icons in the metadata of the modules have been updated.

Specifically there is:

1. Desktop/mobile icon denoting that the current module[id] "follows from" another module
2. Desktop/mobile icon denoting that the current module[id] "leads to" another module
3. Desktop only icon denoting that the current module[id] both "follows from" and "leads to" other modules
4. Mobile only icon denoting that the current module[id] both "follows from" and "leads to" other modules

Here are examples of each of the above in order:
<img width="1121" alt="Screen Shot 2022-01-13 at 09 39 34" src="https://user-images.githubusercontent.com/28573875/149295338-df5bddf6-f916-4e97-a709-b847ca969d22.png">
<img width="1113" alt="Screen Shot 2022-01-13 at 09 40 16" src="https://user-images.githubusercontent.com/28573875/149295468-bb33fd6f-c903-44af-98a3-805073d08225.png">
<img width="1133" alt="Screen Shot 2022-01-13 at 09 42 27" src="https://user-images.githubusercontent.com/28573875/149295822-986adc78-da03-4fd3-a3d5-e5b9df6ba885.png">
<img width="393" alt="Screen Shot 2022-01-13 at 09 42 50" src="https://user-images.githubusercontent.com/28573875/149295900-ce477070-438b-4d8d-b103-22cda4fc0ff2.png">

A link to the correct Figma can be found here: https://www.figma.com/file/3YsBNSmNQmF9LlPJJ7BugX/researchequals.com---Design-System?node-id=1920%3A29085

**Comment by chartgerink** [comment]
This has been superceded by some of the designs implemented already, that are more in line with the homepage (see #241).
