### ISSUE TITLE
After verifying my email, I am taken to the marketing page and not the dashboard

### ISSUE THREAD

**Issue by psobrakseaton** [libscie/ResearchEquals.com#224]
As the title states, this interaction is a little confusing. I think after the verification email, it makes most sense to be returned to the dashboard instead of the marketing page in a logged in state.

**Comment by chartgerink** [comment]
Since #213 is fixed, it no longer is necessary for `/dashboard` to be inaccessible upon verification. 

Would you feel the same if it is referred to `/dashboard` if logged in, otherwise to `/login`?

**Comment by psobrakseaton** [comment]
> Would you feel the same if it is referred to `/dashboard` if logged in, otherwise to `/login`?

Yup! That seems right!

If I am not logged in, I think that it should take me to a the login page. If I have signed up and are logged in I should go back to the dashboard without the verification prompt displaying.

Keep up the good work!
