### ISSUE TITLE
When leaving the focus of the page, suggested followers repopulates

### ISSUE THREAD

**Issue by psobrakseaton** [libscie/ResearchEquals.com#228]
Problem: When you leave the focus of the page (for example when clicking to another tab or window, and then refocus, the suggested followers section repopulates with new people.

Solution: Is it possible to have it only populate when there has been a distint change? Maybe the solution is to be able to dismiss suggestions manually...Open to discussion...

**Comment by chartgerink** [comment]
This is intended use at the moment - refetch happens on window (re)focus. It was previously mentioned in #217, but there excessive refetching during focus happened making it feel buggier than it was.

Dismissing options is technically possible, but requires an additional level of state management that would take a fair amount of additional work that can't be done right now.

I will close the issue as this won't be fixed before launch.

**Comment by psobrakseaton** [comment]
That makes sense that it won't be fixed before launch. I will make a design tweak suggestion for dismissing suggestions in a separate issue to be completed at your convenience post-launch.
