### ISSUE TITLE
Module blocks not extending the full width of the slide-out tray

### ISSUE THREAD

**Issue by psobrakseaton** [libscie/ResearchEquals.com#231]
As you can see in the example image, module blocks 1-2 are only extending part way across the tray, whereas 3 is extending the correct, full width.

<img width="338" alt="Screen Shot 2022-01-14 at 15 52 42" src="https://user-images.githubusercontent.com/28573875/149535500-0a5a9e31-fc38-4c16-b421-88bd95525c3a.png">

**Comment by chartgerink** [comment]
Could you share which browser this was happening in? 

I haven't seen this in Firefox, so my testing is a bit biased..

**Comment by psobrakseaton** [comment]
Good question, I should have specified. This was on Safari.
