### ISSUE TITLE
Create a place for critical links

### ISSUE THREAD

**Issue by psobrakseaton** [libscie/ResearchEquals.com#248]
## Initial Implementation

The idea of this design is to create a place where critical links can be stored. For now, the best place is in a separate settings tab, but I have also documented some design ideas for a future feature update.

Here is the [relevant Figma](https://www.figma.com/file/3YsBNSmNQmF9LlPJJ7BugX/researchequals.com---Design-System?node-id=1837%3A26715).

Here are some specifics:
- [x] Should be visually distinct from the other settings tabs (hence the centered layout).
- [x] Currently in-app the link format is styled just as underlined text, I have tried adding more contrast by changing to indigo (600 for light mode and 500 for dark mode), but they can also follow the styles [laid out here](https://www.figma.com/file/3YsBNSmNQmF9LlPJJ7BugX/researchequals.com---Design-System?node-id=1369%3A1770). 
- [x] The divider breaking up the link block and the Shuttleworth/Mozilla credit should be the same color as other dark mode/light mode content separators (cool-gray-600/cool-gray-300 respectively).

<img alt="Critical Links" src="https://user-images.githubusercontent.com/28573875/150149277-7d949e71-70ef-4866-970a-16029e28c7ef.png">

## Future Designs

I recommend that in the future you look into creating a better dedicated space for helpful content (legal links, documentation, tutorials, keyboard shortcuts, etc.). This can be implemented in a variety of ways ranging from a simple slide-out tray that we already have in the app, to a more complex help feature like some of the examples I will list below.

Regardless, I think fusing the Chatra prompt with a help section would ultimately be the best route possible.

### Examples

<img  alt="Notion Help" src="https://user-images.githubusercontent.com/28573875/150148606-3e3f12ce-987d-4333-9857-f873b3b4033a.png">_Notion_

<img alt="Google Help" src="https://user-images.githubusercontent.com/28573875/150148956-961c2837-8450-4e72-b168-3ff060155749.png">_Google Calendar/Apps_

<img alt="Figma Help" src="https://user-images.githubusercontent.com/28573875/150149109-db4ad04d-fb13-43c6-ac53-181a1dbcb59b.png">_Figma_

**Comment by chartgerink** [comment]
Fixed in #261
