### ISSUE TITLE
pages of research output (with an DOI) should have schema.org annotation to boost SEO

### ISSUE THREAD

**Issue by egonw** [libscie/ResearchEquals.com#294]
# Context
Over the past couple of years I have worked with the [Bioschemas](https://bioschemas.org/) team to add semantic annotation to multiple website. It is an extension in the life sciences of [schema.org](https://schema.org/) which also has annotation for "types" like Computational Tool, Data/Data Set, etc. The annotation is normally autogenerated from content already on the page. 

# Expected Outcome
Published Steps have schema.org/Bioschemas JSON-LD embedded in their pages, to be indexed by all major search engines.

I am happy to support this and will try to find time to make a draft patch at some point.

# Example

This examples comes from the schema.org website and shows the HTML element one would embed somewhere in the HTML page for a `CreativeWork`, possible the simplest solution for any "Step":

```xml
<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "CreativeWork",
  "author": "Sony",
  "contentRating": "Mature",
  "image": "videogame.jpg",
  "name": "Resistance 3: Fall of Man"
}
</script>
```

Many fields are optional and a rich overview is provided at https://schema.org/CreativeWork

**Comment by chartgerink** [comment]
Thanks @egonw!

I think this should indeed be reasonable to add. Do you know how these relate to OpenGraph tags? We already incorporate those for some information, and I don't know if  it would create a redundancy.

In any case, thanks for taking the time to suggest this - it sounds like a good idea at first read 😊

**Comment by egonw** [comment]
I do expect (some) overlap with OpenGraph tags. Thanks for that comment: I'll check them in the current pages, and reply with the mapping/translation to schema.org JSON-DL.

**Comment by egonw** [comment]
@chartgerink, I left a first example here: https://gist.github.com/egonw/636cd4342f79a7c283db6d3b99bae246

A typed it now as CreativeWork, but there are more types. We can map RE types to other types, like Dataset, etc. I need to check that later. There is a long list of info bits that can be added: https://schema.org/CreativeWork

BTW, I mapped `og:image` to `image` now, but plz also check out `thumbnailURL` of schema.org... that too I need to check which is more appropriate.

**Comment by chartgerink** [comment]
Thanks @egonw! I will attempt a basic version now - additional mappings can be added in the future potentially.

**Comment by chartgerink** [comment]
@all-contributors add @egonw for example and ideas
