### ISSUE TITLE
Changing between breakpoints duplicates search input

### ISSUE THREAD

**Issue by Ponjimon** [libscie/ResearchEquals.com#295]
If you change between the breakpoints below and above 680px, the search input can be duplicated.

I don't think it's a major issue since I only seem to being able to reproduce it when changing between the breakpoints pretty fast. Nevertheless, it looks like it could be a memory leak or something that causes this?

https://user-images.githubusercontent.com/770632/151990379-eb7f1496-b6fe-44be-8fb9-642b32b99c55.mp4

**Comment by chartgerink** [comment]
Thanks @ponjimon for reporting this! 

I can recreate this on the root page `/`, partially on `/dashboard` and some other pages. But I cannot reproduce it on a published module like [here](https://www.researchequals.com/modules/hbfx-kmg3). Does the problem persist across all pages for you?

@all-contributors add @Ponjimon for bug

**Comment by Ponjimon** [comment]
@chartgerink I can reproduce it on that link as well. The easiest "trick" to reproduce it is opening the browser's devtools and then toggling between mobile view and normal view using the deticated button:

![image](https://user-images.githubusercontent.com/770632/151995241-d7fe8c00-5bf5-41b0-8c55-709673242cdb.png)


Also, if it helps: I'm running Chrome `97.0.4692.99`
