### ISSUE TITLE
Error Message when Missing a License is Asking for Characters 

### ISSUE THREAD

**Issue by nsunami** [libscie/ResearchEquals.com#297]
I noticed that when a license is not selected, it will show an error message asking for characters.  (`License - Should be at least 1 characters`)
I expected that the error message would show "Required".

![image](https://user-images.githubusercontent.com/17035406/151996345-ca9b8451-9923-424c-92f1-f80c3d239c44.png)

A very small bug, but I wanted to put it out there!

**Comment by chartgerink** [comment]
Thanks Nami! That's good feedback 😊 

@all-contributors add @nsunami for bug
