### ISSUE TITLE
ability to link data management plans to steps

### ISSUE THREAD

**Issue by egonw** [libscie/ResearchEquals.com#301]
Many steps produce data (training data, experimental data, data from standards) or software of some kind, which need to be linked to management plans (aka "SOPs of notebook keeping"). Being able to make such links would be very useful.

**Comment by chartgerink** [comment]
Thanks for the feedback!

Could you provide some examples of such links? I am unfamiliar with these and can benefit from your expertise to help understand what you would expect to be possible.

**Comment by egonw** [comment]
one pointer: https://dmponline.dcc.ac.uk/public_plans

**Comment by chartgerink** [comment]
Thanks! Looks like these are regular URIs so will have to think of a way to persist them. If they are identified with Persistent Identifiers (PIDs) it may be easier to integrate. 

Will mull it over 😊

**Comment by chartgerink** [comment]
We can continue the discussion in #192 - I think there are options to do this in the long run (at the moment everything is a resource question...)
