### ISSUE TITLE
Search colors are not in line with published colors

### ISSUE THREAD

**Issue by chartgerink** [libscie/ResearchEquals.com#304]
Authors get to choose the publication color, but this is currently not reflected in the search results.

![Screenshot 2022-02-04 at 13 35 35](https://user-images.githubusercontent.com/2946344/152530073-9cec3815-cd83-4007-9744-501ff54bd2d1.png)

This requires updating the search results in the navigation bar to include the `displayColor` property.

**Comment by wiksien** [comment]
I would like to fix this.
