### ISSUE TITLE
[bug] Avatars sometimes do not load

### ISSUE THREAD

**Issue by ThomasFKJorna** [libscie/ResearchEquals.com#307]
First off, fantastic project, big fan!

On the "Who to follow" section of my profile the list of people shuffles/refreshes when changing focus (might be intentional) and sometimes the avatars do not load correctly (502 bad gateway)

On Firefox 96.0, MacOs 10.15, 2020 M1 Macbook Air

# video 
(w/ React devtools on if that helps, was too lazy to turn it off. cw: rapidly changing images)

https://user-images.githubusercontent.com/21983833/152965415-24d0f893-b972-4b8e-88b7-160bd49f382a.mov

# Error
```
GEThttps://eu.ui-avatars.com/api/?rounded=true&background=574cfa&color=ffffff&name=dirkriehle
[HTTP/2 502 Bad Gateway 196ms]

	
GET
	https://eu.ui-avatars.com/api/?rounded=true&background=574cfa&color=ffffff&name=dirkriehle
Status
502
Bad Gateway
VersionHTTP/2
Transferred5,89 KB (5,38 KB size)
Referrer Policystrict-origin-when-cross-origin

    	
    HTTP/2 502 Bad Gateway

    date: Tue, 08 Feb 2022 10:02:26 GMT

    content-type: text/html; charset=UTF-8

    set-cookie: cf_ob_info=502:6da405bc6a051764:EWR; path=/; expires=Tue, 08-Feb-22 10:02:56 GMT

    set-cookie: cf_use_ob=443; path=/; expires=Tue, 08-Feb-22 10:02:56 GMT

    x-frame-options: SAMEORIGIN

    referrer-policy: same-origin

    cache-control: private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0

    expires: Thu, 01 Jan 1970 00:00:01 GMT

    cf-ray: 6da405bc6a051764-EWR

    server: cloudflare

    X-Firefox-Spdy: h2
    	
    Accept
    	image/avif,image/webp,*/*
    Accept-Encoding
    	gzip, deflate, br
    Accept-Language
    	en-US,en;q=0.5
    Connection
    	keep-alive
    DNT
    	1
    Host
    	eu.ui-avatars.com
    Referer
    	https://www.researchequals.com/
    Sec-Fetch-Dest
    	image
    Sec-Fetch-Mode
    	no-cors
    Sec-Fetch-Site
    	cross-site
    TE
    	trailers
    User-Agent
    	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:96.0) Gecko/20100101 Firefox/96.0
```

**Comment by chartgerink** [comment]
Welcome @ThomasFKJorna and thanks for reporting this. There is nothing lazy in you reporting - I appreciate any time you spend on doing this 😊 

The issue of the avatar loads is popping up a bit more frequently than I had expected - it seems like [`https://eu.ui-avatars.com/`](https://eu.ui-avatars.com/) can't handle it as well. Do you feel it is too annoying or more a minor annoyance? (or something else)

With respect to the shuffling of the who to follow, it is intended at this point, but not set in stone. We do an auto refresh on window focus to ensure the feed is up to date, and then it also shuffles the suggested follows. With that information, would you prefer it to be different?

**Comment by chartgerink** [comment]
@all-contributors add @ThomasFKJorna for bug

**Comment by chartgerink** [comment]
It appears [`ui-avatars`](https://ui-avatars.com/) has improved their services to such a degree this is no longer happening. I couldn't reproduce this with a gazillion reloads. 😊
