### ISSUE TITLE
escaping of the JSON-LD is wrong, in two ways

### ISSUE THREAD

**Issue by egonw** [libscie/ResearchEquals.com#313]
The following code is a good start and the JSON-LD content generally looks great:

There is two current issues that should be easy to fix (tho, not sure how to do it):

1. right now the full JSON is escaped in the HTML, but the quotes in the HTML should overall really be quotes and not HTML escape coded. I think the overall escaping is triggered by the backtick at the end on this line:

https://github.com/libscie/ResearchEquals.com/blob/fcbe4f7809e0a2c95fee74683d889d1e856687e0/app/pages/modules/%5Bsuffix%5D.tsx#L351

2. the quotes *inside* field values should be escaped, however, in the title and definition, where quotes can be part in the these field values. This is for example on this line:

https://github.com/libscie/ResearchEquals.com/blob/main/app/pages/modules/%5Bsuffix%5D.tsx#L357

In pseudocode, this should look something like this:

```
"description": "${module.description.replace("\"","&quot;")}",
```

**Comment by chartgerink** [comment]
Thanks @egonw - I forgot to validate. I am not 100% sure I understand point 1 - this is the HTML I see and it contains no escapes?

```html
<script type="application/ld+json">
           {
             "@context": "https://schema.org",
             "identifier": "10.53962/k5e5-t1dn",
             "@type": "CreativeWork",
             "title": "Story of a Civic Sentinel",
             "description": "The SensJus project launched a short graphic novel recounting the story of a civic sentinel, which tells the struggle of many and a lesson of hope.
The story begins in a land, afflicted by oil extraction. A reality made of silent contamination, of official data that hide the truth, and of unheard complaints. On this landscape of unspoken or inaccessible information, the people who cultivate the land, breed animals, or simply live there are divided between those who want to discover and denounce, and those who remain silent, captured by the system. 'Story of a civic sentinel' tells the challenges encountered by those who decide to investigate into the contamination, monitor it, and fight for the truth to be known.
The novel can be downloaded for free at this link:
 https://drive.google.com/file/d/1s9-M4-Yj7JtbVfY_vrH_AxU46gm2VzEI/view?usp=sharing 

The novel is also available in Spanish and Italian, and these versions can be found on the SensJus page.",
             "url": "https://doi.org/10.53962/k5e5-t1dn"
           }
          </script>
```

I see the issue of 2 - I will add a sanitizer to that end. 

Do you have a preferred validator that you use? I am now trying out [JSON-LD playground](https://json-ld.org/playground/) but maybe you have a more informed preference 😊

**Comment by egonw** [comment]
Yes, the link is in the original pull request. I should have linked to that. I'll look it up tomorrow when back behind my laptop.

**Comment by egonw** [comment]
Sorry for the delay, but the schema.org validator can be found here: https://validator.schema.org/

**Comment by chartgerink** [comment]
Thanks @egonw 🤗 I see the issue in the validator much more clearly!

I will attempt this again now - and validate before merging this time.
