### ISSUE TITLE
Cannot add references by DOI formatted as an URL

### ISSUE THREAD

**Issue by nsunami** [libscie/ResearchEquals.com#325]
I was trying to add references to a module, but I couldn't do so by a DOI in an URL format (e.g., I cannot use `https://doi.org/10.1037/1089-2680.10.3.229`, but I can use `10.1037/1089-2680.10.3.229`)

![image](https://user-images.githubusercontent.com/17035406/153645470-706a35ca-0026-46a5-a71c-4617c5644141.png)

It would be nice to add references using either string.

**Comment by chartgerink** [comment]
Thanks @nsunami for another valuable contribution! 

Would you be interested in making a PR for this? If so, I am happy to assign it. Otherwise, I'm also happy to assign this to myself 😊

**Comment by nsunami** [comment]
Sure! I can try! I can see that the DOI is matched here?
https://github.com/libscie/ResearchEquals.com/blob/6d043297c9a053a2abf1b843103700d24927db02/app/modules/components/ModuleEdit.tsx#L485
 
I wonder if we remove the start of a string operator---would that work?
```
{query.match(/10.\d{4,9}\/[-._;()/:A-Z0-9]+$/i) ? (
```

**Comment by nsunami** [comment]
I was hoping that we can capture the `10.1371/journal.pone.0127502` part from the string like `https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0127502`. Just submitted a PR! I could not run the app on local but hope this captures the gist.
