### ISSUE TITLE
`React.render`warning in `Autocomplete.tsx`

### ISSUE THREAD

**Issue by chartgerink** [libscie/ResearchEquals.com#364]
As mentioned [here](https://github.com/libscie/ResearchEquals.com/issues/326#issuecomment-1039130069), the [`Autocomplete`](https://github.com/libscie/ResearchEquals.com/blob/main/app/core/components/Autocomplete.tsx) component uses the render method, which has been updated in React@18. 

The warning does not break anything at this point, but does prevent utilizing the full capacity of React@18. It would be helpful to resolve this warning before it becomes a breaking issue.

```
Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. 
Until you switch to the new API, your app will behave as if it's running React 17. 
Learn more: https://reactjs.org/link/switch-to-createroot
```

[Link to React docs on this](https://reactjs.org/link/switch-to-createroot). This seems to be relatively minor but my attempts didn't succeed 🥎  If you know how to fix this, we welcome a PR!

**Comment by chartgerink** [comment]
Closing this as a wontfix. We can revisit it if it is important again for whatever reason.

**Comment by nsunami** [comment]
I found this and wanted to comment here in case we pick it up again in the future. 
(Also closing this as not planned, not completed)
https://github.com/algolia/autocomplete/pull/969

**Comment by nsunami** [comment]
I'm re-opening this because I think we can fix this now! (I hope I'm not jinxing 😆)
