### ISSUE TITLE
The reset password page is exposed 

### ISSUE THREAD

**Issue by nsunami** [libscie/ResearchEquals.com#368]
I noticed that the page to reset the password is exposed. 

https://www.researchequals.com/reset-password

I expected that accessing this URL without logging in (and without initiating the reset password process) would re-direct to the login page.

Maybe a solution would be to verify that the token is there, and if not redirect to the login page?

**Comment by chartgerink** [comment]
Thanks for reporting @nsunami!

It is exposed but functionless if there is no valid token included in the URL. We could add indeed add a redirect to the page logic if you'd like - would you be interested in making a PR for that? 😊 I think it's a good improvement - and it's perfectly okay if you don't feel like doing it 😉

**Comment by nsunami** [comment]
Submitted a PR! It is in the right direction. 😊
