### ISSUE TITLE
Account verification when verifying from a different browser without the session information

### ISSUE THREAD

**Issue by psobrakseaton** [libscie/ResearchEquals.com#48]
While testing the sign up procedure, I utilized Chrome for the sign up form and when I clicked "Verify email" in the email it opens in Safari as it is my default browser and my account isn't verified. 

I could imagine quite a few cases where verification happens on a separate browser or device and I think this issue could resurface with some regularity.

**Comment by chartgerink** [comment]
Thanks @psobrakseaton!

In order to prevent verification outside of the user's control, I am considering adding that users need to be logged in to verify their email. This will also permit immediate redirect to dashboard.
