### ISSUE TITLE
Implement a file viewer on the drafts page

### ISSUE THREAD

**Issue by nsunami** [libscie/ResearchEquals.com#488]
I was wondering if implementing a file viewer on the drafts page would be a nice enhancement.

Currently, we cannot see a file uploaded to a draft:

<img width="928" alt="image" src="https://user-images.githubusercontent.com/17035406/176966986-5336dd99-cac6-45ac-9a7a-72d633247bde.png">

Of course, we can always download the file and check it. But, since we have a file viewer for the published modules, it would also make sense to implement here. People may want to preview how it would look like before publishing. 

Thought about this while working on #481.

**Comment by chartgerink** [comment]
Great suggestion @nsunami! 

This should be feasible as we can factor out the code from https://github.com/libscie/ResearchEquals.com/blob/b8e21f84e404eede7202113aa0363fd59c03552c/app/pages/modules/%5Bsuffix%5D.tsx#L279 and implement it in two ends.

One additional thought I'm having is whether we should have a toggle for previewing supporting files in a similar way  (although that might be a separate issue/discussion)? What do you think?

**Comment by nsunami** [comment]
@chartgerink Not sure why I missed your comment!

> One additional thought I'm having is whether we should have a toggle for previewing supporting files in a similar way (although that might be a separate issue/discussion)? What do you think?

I think presenting supporting files can be too much if they are many.
One thing we could improve may be to open a new tab to show the files?

Currently, clicking the title of a supporting file downloads the supporting file. The behavior is the same as for the download button. 
<img width="489" alt="image" src="https://user-images.githubusercontent.com/17035406/182366275-f70f55d9-fef1-4bfb-907f-56d625c7179e.png">
This would mean removing `download` from here
https://github.com/libscie/ResearchEquals.com/blob/eddbcbce3697a933ea6e2fabf11ea16fc365a650/app/modules/components/ViewFiles.tsx#L7-L13

To like this:

```
      <a
        href={url}
        className="mr-1 flex flex-grow rounded border border-gray-100 px-2 py-1 text-sm font-normal leading-4 text-gray-900 shadow-sm hover:bg-gray-100 dark:border-gray-600 dark:text-gray-200 dark:hover:bg-gray-700"
        target="_blank"
        rel="noreferrer"
      >
```
