### ISSUE TITLE
Remove redundant ternary operators

### ISSUE THREAD

**Issue by chartgerink** [libscie/ResearchEquals.com#546]
A ternary operator is ([according to MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator))

> ... the only JavaScript operator that takes three operands: a condition followed by a question mark ( ? ), then an expression to execute if the condition is truthy followed by a colon ( : ), and finally the expression to execute if the condition is falsy.

There's a lot of ternary operators spread throughout the application that follow this pattern:

```
x === "something" ?
   <>content</> :
   ""
```

Based on feedback from @nasainsbury, it seems like we could simplify the code in those cases:

```
x === "something && <>content</>
```

This would reduce the amount of (potential) confusion in the ternary logic. Unchanged functionality would need to be checked upon implementation. 

This is a great issue to work on if you'd like to contribute to the project but don't want to dive in real deep. This contribution will still benefit the project and we'd much appreciate if you choose to do it 🙏

**Comment by nsunami** [comment]
During the review on the collections feature, I found a similar place for optimization (mentioned https://github.com/libscie/ResearchEquals.com/pull/685#discussion_r977794577)

**Comment by chartgerink** [comment]
Closing because this has gotten stale.
