### ISSUE TITLE
HTML entities in title metadata 🐛 

### ISSUE THREAD

**Issue by chartgerink** [libscie/ResearchEquals.com#625]
### URL of the Page

https://researchequals.com/drafts

### What happened?

In PR #610 we added DataCite metadata ingestion (YAY!). During testing I noticed that there are HTML entities like `&amp;` that can pop up in citations.

Preferably, we would parse these either before ingesting the metadata in our database, when presenting the metadata, or both to be super-safe.

The [`he` library](https://github.com/mathiasbynens/he) (what a name 🤔 ) might be a good option for doing this without requiring a DOM element.

### Steps to reproduce

1. Go to `/drafts`
2. Try to add `10.5281/zenodo.4946933` as a reference
3. Check the citation for the title: `CSCCE Community Profile: Code for Science &amp; Society Event Fund`

### What browser(s) did you use?

Firefox

### Anything else?

🥒

**Comment by nsunami** [comment]
Another example DOI here: `10.1080/02732173.2021.1875090`
