### ISSUE TITLE
Add metadata for Zotero ingestion

### ISSUE THREAD

**Issue by chartgerink** [libscie/ResearchEquals.com#626]
In order to improve saving ResearchEquals modules to Zotero, we could upgrade the metadata exposed by default in the `<head>` tag. 

For reference, see some of [the documentation from Zotero](https://www.zotero.org/support/dev/exposing_metadata).

This issue tracks the work on this, and potential questions that come up while implementing this. Sub-issues may be added as they come up.

### Resources

-  [Zotero translators](https://www.zotero.org/support/translators) (maybe relevant?)

**Comment by nsunami** [comment]
I'm taking a first tab at this for the module, by creating a component that renders the `<meta>` tags.

**Comment by nsunami** [comment]
According to the [Zotero doc](https://www.zotero.org/support/dev/exposing_metadata#:~:text=expose%20your%20metadata%3A-,Embedded%20Metadata,-The%20%3Cmeta%3E%20tags), there are 25 embedded metadata fields that we can use.

1. Title: citation_title
2. Date: citation_date (preferred), citation_publication_date, citation_cover_date, citation_online_date, citation_year
3. Publication: citation_journal_title
4. Journal Abbreviation: citation_journal_abbrev
5. Book Title or Proceedings Title: citation_book_title, citation_inbook_title
6. Pages: citation_firstpage and citation_lastpage
7. Volume: citation_volume
8. Issue: citation_issue
9. Series: citation_series_title
10. Publisher: citation_publisher
11. DOI: citation_doi
12. ISBN: citation_isbn
13. ISSN: citation_issn, citation_eIssn
14. PMID: citation_pmid
15. URL: citation_public_url, citation_abstract_html_url, citation_fulltext_html_url
16. Embedded Metadata can also find the URL in a <link rel=“canonical”> tag or use the page URL.
17. Abstract: citation_abstract
18. Language: citation_language
19. Conference Name: citation_conference_title, citation_conference
20. University (for theses and dissertations): citation_dissertation_institution
21. Institution (for reports): citation_technical_report_institution
22. Report Number: citation_technical_report_number
23. Creators: citation_author, citation_authors, citation_editor, citation_editors
24. Full-Text PDF attachment: citation_pdf_url
25. Tags: citation_keywords (semicolon-separated)
