### ISSUE TITLE
Non-responsiveness on homepage🐛 

### ISSUE THREAD

**Issue by chartgerink** [libscie/ResearchEquals.com#633]
### URL of the Page

https://researchequals.com

### What happened?

When I try to use the search bar on the homepage, it doesn't show up. I only see a slight thing pop up on the left side of my screen. It works fine on other pages

### What browser(s) did you use?

Firefox, Safari, Microsoft Edge

### Anything else?

@nsunami can you try to replicate this issue? It seems new and I'm not sure why...

EDIT: Might be because of the translation package? Should test this out...

**Comment by nsunami** [comment]
I see the search bar, when I focus on it. But I cannot type it. I'm guessing it is related to destructing behavior to on lazy component in react? 


<img width="764" alt="image" src="https://user-images.githubusercontent.com/17035406/185141826-120322ca-b358-4262-9970-5090634e42e1.png">


I can type in the detached mode, but results are not showing up.
<img width="489" alt="image" src="https://user-images.githubusercontent.com/17035406/185142061-d88bdd0b-c094-4413-88fe-d244978329a7.png">
