### ISSUE TITLE
Blitz 2.0 upgrade trial run

### ISSUE THREAD

**Issue by chartgerink** [libscie/ResearchEquals.com#635]
[Blitz release the beta of `v2.0.0`](https://github.com/blitz-js/blitz/releases/tag/v2.0.0-beta.1), which is [a pivot from their previous approach](https://github.com/blitz-js/blitz/discussions/3075).

It would be good to try out the upgrade and evaluate thoroughly whether everything works as expected. We might need to do some manual adjustments, but this is an important upgrade for us.

It looks like it should be an automated upgrade from `blitz`'s side: 

```
npx @blitzjs/codemod upgrade-legacy
```

Opening this issue to track the discoveries and prepare for a smooth and confident upgrade. It may also resolve some other issues so it's worth cross checking (e.g., it may unblock the Typescript upgrade in #533).

**Comment by nsunami** [comment]
Documenting here what happens after running the upgrade.

1. Run:
```
npx @blitzjs/codemod upgrade-legacy
```

The script completes without a failure. 

2. Run `npm install` 

3. Run `npm run dev` leads to an error:

```
(node:22647) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
error - Failed to load next.config.js, see more info here https://nextjs.org/docs/messages/next-config-error
/Users/nami/git/ResearchEquals.com/next.config.js:2
import { sessionMiddleware, simpleRolesIsAuthorized } from "blitz";
^^^^^^

SyntaxError: Cannot use import statement outside a module
```


4. Fix the `next.config.js` by deleting:
```
import { sessionMiddleware, simpleRolesIsAuthorized } from "blitz";
```

5. Run `npm run dev` leads to a bunch of module not found errors, due to the changes in the path:
```
error - ./pages/index.tsx:28:0
Module not found: Can't resolve '../core/components/Navbar'
  26 | import ReactTooltip from "react-tooltip"
  27 | 
> 28 | import Navbar from "../core/components/Navbar"
```
The next step is to change the path.

Also, committing fails because of the pre-commit hook error:

```
ESLint couldn't find the config "eslint-config-next" to extend from. Please check that the name of the config is correct.
```

(I'll continue updating this comment if I make any progress.)

**Comment by nsunami** [comment]
We are focusing on this issue in October! We'll start with studying where the blitz package is and strategize.

**Comment by chartgerink** [comment]
@nsunami do you have any reportback on investigating the details of this? I remember us chatting about you doing a bit of research on this so we can better understand the risks of upgrading while it's in beta.

If I missed something elsewhere, I apologize - still getting up to speed!
