### ISSUE TITLE
Fix the Postmark template for the sign-up/verification emails

### ISSUE THREAD

**Issue by nsunami** [libscie/ResearchEquals.com#646]
Currently, the layout of the sign-up/verification emails is overflowing horizontally, as shown in the screenshots below. 

This issue happened in viewing the email in:

1. Apple Mail Version 16.0 (3696.120.41.1.1)
2. Proton mail online app (mail.proton.me)

A fix would be to update the template of the Postmark. But, I'm not sure the best place to store it (Would it be best to store a template in this repo? If so, can we use that template in the Postmark API?)

### Sign-up

<img width="569" alt="image" src="https://user-images.githubusercontent.com/17035406/186930044-c2267968-d604-485a-a52c-93d45f356260.png">

### Change email

<img width="578" alt="image" src="https://user-images.githubusercontent.com/17035406/186930438-709351d9-f5de-455e-9f6d-d26fab0635a6.png">

### Forgot password

<img width="582" alt="image" src="https://user-images.githubusercontent.com/17035406/186931434-3ce28de1-6d06-439e-8735-a5fcfa8a729c.png">

_Originally posted by @nsunami in https://github.com/libscie/ResearchEquals.com/pull/643#pullrequestreview-1087082545_

**Comment by nsunami** [comment]
The problem is that in the "action_url" stretches out because it does not have a breaking character. 


Currently:

HTML:
```html
      <p class="sub">If you’re having trouble with the button above, copy and paste the URL below into your web browser.</p>
      <p class="sub">{{action_url}}</p>
```

CSS:
```css
    p.sub {
      font-size: 13px;
    }
```

We may need to do two things:

1. Use `overflow-wrap: break-word;` to the tag that's wrapping the `action_url`
2. Fix the width of the element

**Comment by nsunami** [comment]
@chartgerink Assigning you here since I don't have access to Postmark 🙏

**Comment by chartgerink** [comment]
Seems to work!

![image](https://user-images.githubusercontent.com/2946344/208687289-8be2c76f-a251-47a0-a281-a7e5f84c326c.png)

Closing as this is now fixed. Also fixed this in password reset.
