### ISSUE TITLE
Collections modal prevents scrolling upon cloes 🐛 

### ISSUE THREAD

**Issue by chartgerink** [libscie/ResearchEquals.com#693]
### URL of the Page

https://researchequals.com

### What happened?

I can no longer scroll through a page if I had the collections modal open. I need to reload the page.

### Steps to reproduce

1. Go to a page that can be scrolled on.
2. Open the collections modal any way (e.g., in the navigation bar next to the profile avatar)
3. Close the collections modal
4. Try to scroll

### What browser(s) did you use?

Firefox, Safari

### Anything else?

![](https://media.giphy.com/media/LM897heiIp22wvfr8T/giphy.gif?cid=ecf05e47n8nc569jn244f8gpqfoz4po9841zqnsf43rp2s98&rid=giphy.gif&ct=g)

**Comment by nsunami** [comment]
@chartgerink Are working on this via #685?

**Comment by chartgerink** [comment]
This is already fixed there yes 👍 

Was easier than expected - it was an artefact of the state management which was unecessary. See also https://github.com/libscie/ResearchEquals.com/pull/685/commits/267945e4df482ee06b659d2fa7fea80dcdfaa6ab

**Comment by nsunami** [comment]
Great, thanks! I'm removing myself as an assignee here then 👍
