### ISSUE TITLE
A blank space below the draft page when uploading a tall main file   🐛 

### ISSUE THREAD

**Issue by nsunami** [libscie/ResearchEquals.com#696]
### URL of the Page

https://www.researchequals.com/drafts

### What happened?

When uploading a tall main file (such as a tall image) in the draft view, there will be a blank space below the screen. 

We may want to check the overflow. 

### Steps to reproduce

1. Add a draft
2. Upload a tall image (The test image I used was 1242 × 2208)
3. Scroll down the screen (I had to scroll on the sidebar. Not on the image itself).

### What browser(s) did you use?

Chrome

### Anything else?

I noticed this while working on the Dependabot upgrade for Uploadcare (https://github.com/libscie/ResearchEquals.com/pull/653)

![researchequa-dependabot-1fdhjo herokuapp com_drafts_suffix=mpk0-yp8w(iPad Mini) (2)](https://user-images.githubusercontent.com/17035406/189712603-2c735a81-bd8f-44f7-8a60-86b413176256.png)

**Comment by chartgerink** [comment]
Good catch! Hadn't seen this one before.
