### ISSUE TITLE
Horizontal scroll bar appears on the menu when the window is narrow 🐛 

### ISSUE THREAD

**Issue by nsunami** [libscie/ResearchEquals.com#713]
### URL of the Page

https://www.researchequals.com/

### What happened?

When the window is narrow, the menu area shows a horizontal scroll bar:

<img width="752" alt="image" src="https://user-images.githubusercontent.com/17035406/190680048-8ae65340-b1a5-47d8-bded-83fdd2624f08.png">

(when viewing with the width of ~800 px)

### Steps to reproduce

1. Go to https://www.researchequals.com/
2. Log in
3. Adjust the window width to 800px

### What browser(s) did you use?

Chrome

**Comment by chartgerink** [comment]
What do you think should happen instead? From my point of view this is expected behavior at the moment, because it's scrollable. Happy to explore adjustments as this menu is getting a bit cluttered (collections will also be added...)

**Comment by nsunami** [comment]
Chris and I talked and we decided to set the breakpoint identical to the nav bar. 👍  I will try implementing
