### ISSUE TITLE
Soft-code the version number of the `pdfjs-dist` package 

### ISSUE THREAD

**Issue by nsunami** [libscie/ResearchEquals.com#714]
Currently, the version number of the `pdfjs-dist` package is hard-coded, and this requires a manual update as the package's version changes. 

- [Wiki](https://github.com/libscie/ResearchEquals.com/wiki/Dependencies#pdfjs-dist)
- Component: [app/core/components/FilePreviewer.tsx](https://github.com/libscie/ResearchEquals.com/blob/562f69e16cdff59054fc42191a5a0d10f4da23bd/app/core/components/FilePreviewer.tsx#L37)

I think it would be better to explore ways to get this hard-coded, to alleviate the effort for maintenance.

One approach is to expose the version number of the loaded package to the client, via editing the `blitz.config.ts` file.

**Comment by chartgerink** [comment]
Sounds like a great idea @nsunami! 😊
