### ISSUE TITLE
Add `db seed` to Heroku test deploys

### ISSUE THREAD

**Issue by chartgerink** [libscie/ResearchEquals.com#724]
We recently had a hick-up in merging PRs, where something resulted in an error in production. 

One reason was that the production environment failed during `blitz db seed`, which is not run in the Heroku deployments right now. This means that the auto-deploy made us overconfident.

This can be resolved by adding `npx blitz db seed` to the `./Procfile`.

**Comment by nsunami** [comment]
Taking a note about why the app deploys on Heroku but not on AWS/`flightcontrol`. 📓

Currently, the production behavior is determined by the `flightcontrol.json` file. This script applies the db migration, seeding and building (`npx blitz prisma migrate deploy && npx blitz db seed && npm run build`). On the other hand, the Heroku script (`./Procfile`) used to only migrates the db, but do not do seeding  `npx blitz prisma migrate deploy`. Synching up these script would minimize the discrepancy between the Heroku review app environment and the production environment. 


On a side note, I wonder if it would be useful to do the db migration and seeding when testing on local. My initial idea is to add  `npx blitz prisma migrate dev && npx blitz db seed` (not deploy) into the `dev` command in the `package.json` file. But, I'm not 100% sure if that's possible & recommended.
