### ISSUE TITLE
Audit the dependency,`@floating-ui/dom`

### ISSUE THREAD

**Issue by nsunami** [libscie/ResearchEquals.com#725]
I was working on the PR #722 for upgrading `@floating-ui/dom`, but I was not able to figure out where or whether this dependency is currently used. Making an issue here to track the audit process. If this is not currently used, we can remove it.

> The PR #391 mentions that `@floating-ui/dom` is used in the marketing page tooltips, but I was unable to find it in the current version.

_Originally posted by @nsunami in https://github.com/libscie/ResearchEquals.com/issues/722#issuecomment-1252899544_

**Comment by nsunami** [comment]
As @chartgerink mentioned in https://github.com/libscie/ResearchEquals.com/pull/722#issuecomment-1255046786, this dependency is being used like this:

> ![image](https://user-images.githubusercontent.com/17035406/191774793-cd0ca805-5846-4a73-89e0-e5645ad5a650.png)

**Comment by nsunami** [comment]
I added a description about this dependency to [our Wiki](https://github.com/libscie/ResearchEquals.com/wiki/Dependencies#floating-uidom).

**Comment by chartgerink** [comment]
Thanks @nsunami! I think we can close this then?

Note: This could be deprecated potentially when we have the new marketing page that is being developed. We'll have to doublecheck of course.

**Comment by nsunami** [comment]
@chartgerink  Welcome!  And thanks for the note about the upcoming marketing page!

Just to double-check—is `@floating-ui/dom` somehow interact with `react-tooltip`? Looking at the [`index.tsx` file](https://github.com/libscie/ResearchEquals.com/blob/deb59226a5d8531a8c463708845f9bcf1bbb09b7/app/pages/index.tsx#L304-L306), `react-tooltip` is used around the tooltip content. I realized this while working on the dependabot upgrade for `react-tooltip` https://github.com/libscie/ResearchEquals.com/pull/825, and I just wanted to make sure before closing this issue.

**Comment by chartgerink** [comment]
Oh haha - it seems like it's not being used indeed. You could try removing it and see whether things work as expected? 

I might've forgotten to remove it after exploring it as an option and never double checking the dependency list.

**Comment by nsunami** [comment]
Got it! Will do! 👍
