### ISSUE TITLE
Approval email with the wrong name 🐛 

### ISSUE THREAD

**Issue by chartgerink** [libscie/ResearchEquals.com#730]
### What happened?

I received an email about an author approving a module, but it was in my name (where I'd previously approved that module).

It seems like something is going wrong in terms of the email sending. We should double check and test multi-author situations and the email sending a bit more.

### Anything else?

![](https://media.giphy.com/media/bdTxWolHXUtbi/giphy.gif?cid=ecf05e47s0ee41axc61r9jvg4w1fqvzxp1uinu084utmsagq&rid=giphy.gif&ct=g)

**Comment by chartgerink** [comment]
I got a report from a person using the platform that this error occurred for them. It might look like everything is fine in the test environment because of using similar names for your different test accounts (I had this issue!).

The reply-to field is correct - it is set that way intentionally right now 😊

**Comment by nsunami** [comment]
I tried sending an invitation email to my second account again today, but I did not receive an email. (quirrel-related?) I also saw that my quirrel dashboard was not showing any tasks. It's possible that my environment is not good.

**Comment by chartgerink** [comment]
Another report of this - I just got an email and I def didn't approve one.

![Screenshot 2022-11-14 at 13 43 16](https://user-images.githubusercontent.com/2946344/201663197-da939418-ee97-465f-8b2c-3878aaabcdcb.png)

It's not selecting the right name so should be a quick fix. Bumping this for priority too.

**Comment by nsunami** [comment]
I'm trying to reproduce the issue here:


1. Create a draft in Account 1
2. Invite Account 2 (email verified & consented to receiving emails)
3. The invitation email looks normal ✅ 
4. In Account 2, approve the draft 
5. I was unable to receive the approval email to my Account 2 on my test environment ❓  

Looking more now...

```
(node:18489) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 pmessage listeners added to [RedisMock]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
``

**Comment by nsunami** [comment]
I think I finally have a replicable step for this.

1. Prepare two accounts (with email settings turned on)
2. Have Account 1 create a draft and add Account 2 as a co-author.
3. Account 2 approves the co-authorship
4. Account 2 approves the draft 
5. In Account 1, change the main file, and re-approve the draft
6. Email will be sent to Account 1, saying that Account 1 approved the draft, as expected.
7. However, an email will be sent out to Account 2, that Account 2 approved the module, while in reality, Account 1 was the one that approved the module.
