### ISSUE TITLE
Research if we can test Stripe on Heroku Test app

### ISSUE THREAD

**Issue by nsunami** [libscie/ResearchEquals.com#736]
Currently, we cannot test Stripe on a Heroku review app. It would be better if we can do so there.

A possible solution is to create a webhook via Stripe API as we deploy the app to Heroku.

**Comment by nsunami** [comment]
Now that we have documented a way to test Stripe, it's time for figuring out on Heroku.

Remaining questions:

1. How to make the URLs of the Heroku review app predictable? It looks like we can set the URL of the Heroku app predictable, dependent on the PR number (e.g., `researchequals-review-pr123.herokuapp.com`). If we can get this URL during the build phase, we can pass this URL to Stripe CLI (`stripe listen --forward-to researchequals-review-pr123.herokuapp.com/api/stripe_webhook`).
2. How to run Stripe CLI on a review app. I'm not sure if we could run `stripe listen ...` on Heroku. I assume we need to tweak `Procfile` for this.

**Comment by chartgerink** [comment]
Thanks Nami! We discussed this in planning and given that this is currently not planned I'm closing this issue. We can reopen if need be.

**Comment by nsunami** [comment]
Sounds good!
