### ISSUE TITLE
Onboarding quest for collections returns to dashboard 🐛 

### ISSUE THREAD

**Issue by chartgerink** [libscie/ResearchEquals.com#737]
### URL of the Page

https://www.researchequals.com/dashboard

### What happened?

Tried to create a collection but was returned to dashboard, instead of to the Stripe checkout session. Seems like there is something in the logic of what's getting passed to the `CollectionsModal` that needs fixing 😅 

### Steps to reproduce

1. Go to dashboard
2. Hit create collection
3. Select Collaborative or Community
4. Try to "Pay and Create"

### What browser(s) did you use?

Firefox, Other

**Comment by nsunami** [comment]
On my Chrome and Firefox, I could not replicate the issue. The checkout session is being presented as expected:



https://user-images.githubusercontent.com/17035406/192607863-9835eefc-3695-474c-82ca-346cc020bdba.mov

**Comment by chartgerink** [comment]
Sorry - I hotfixed this before I left for vacation but forgot to link the PR to the issue 😅 

https://github.com/libscie/ResearchEquals.com/pull/741
