### ISSUE TITLE
Cannot click "Got it" link after agreeing to receive email notifications  🐛 

### ISSUE THREAD

**Issue by nsunami** [libscie/ResearchEquals.com#738]
### URL of the Page

https://www.researchequals.com/dashboard

### What happened?

I noticed that after clicking yes 👍 to receive email notification, I cannot click "Got it!" button on the confirmation (as below). 

<img width="469" alt="image" src="https://user-images.githubusercontent.com/17035406/192012979-bd92d495-61f2-4668-bf63-e23fd2d6af77.png">

### Steps to reproduce

1. Go to dashboard with an account that has not completed the onboarding quest for email notifications
2. Select "Yes" to receive email notifications
3. Cannot click "Got it!" (I expected that we can close the card by clicking this.)

### What browser(s) did you use?

Chrome

**Comment by chartgerink** [comment]
Thanks for writing this up!

This was not intended to be clickable - understand that the link-esque styling made it look that way. I will check the PR and see how it works.
