### ISSUE TITLE
Markdown files are coming back as a binary from Uploadcare (not `text/markdown`)  🐛 

### ISSUE THREAD

**Issue by nsunami** [libscie/ResearchEquals.com#781]
### URL of the Page

https://www.researchequals.com/drafts

### What happened?

When getting the uploaded `.md` file from Uploadcare, the MIME type comes out as binary (application/octet-stream). 

<img width="1127" alt="image" src="https://user-images.githubusercontent.com/17035406/193868939-95a8efbf-4e09-4efa-8774-70b54adca806.png">

This is problematic for rendering the preview, since we rely on the file's MIME type being `text/markdown`. 

Subsequently, the file is not previewed:

<img width="682" alt="image" src="https://user-images.githubusercontent.com/17035406/193869410-5462c972-f8b6-4ed5-9c27-36232e91cc7b.png">

### Steps to reproduce

1. Create a draft
2. Upload a`.md` file as the main file

### What browser(s) did you use?

Chrome

### Anything else?

I can see that the published module on production shows the markdown file.

For example, [this module](https://www.researchequals.com/modules/spj3-x65) previews the markdown content just fine. 

<img width="934" alt="image" src="https://user-images.githubusercontent.com/17035406/193870151-c308d2a1-89d1-4932-b2d3-9bd8fc65d566.png">

But, in my local dev environment, even published modules are not previewing:
<img width="916" alt="image" src="https://user-images.githubusercontent.com/17035406/193870298-c5e77928-750b-42a6-9171-2569bbe9af93.png">

**Comment by nsunami** [comment]
It would be helpful to see if the file uploaded to Uploadcare is registered as markdown or binary on their end.

**Comment by chartgerink** [comment]
Uploadcare has this file registered as `application/octet-stream` and others as `text/markdown` (those that preview). 

What OS are you running? For me it all works when uploading so I cannot reproduce at the moment. In essence the preview functionality is working but it looks like the mimetype is not properly registered upon upload (hence retrieval).

Note: I downloaded your `test-markdown.md` from Uploadcare and uploaded it - it did register `text/markdown` at that point.

**Comment by nsunami** [comment]
Thanks for checking, @chartgerink!

I was using MacOS 12.6

I checked it on my Chrome, and and also with my incognito mode on the upload, but it did not resolve the issue... not sure why



https://user-images.githubusercontent.com/17035406/197219552-548bdf13-6f35-4e25-aa99-d1256be8c172.mov

[test-markdown.md](https://github.com/libscie/ResearchEquals.com/files/9839929/test-markdown.md)

**Comment by chartgerink** [comment]
Could you run `file --mime <filepath>` in your terminal for the specific file? It might be that there is no bug on our end/Uploadcare but something's happening at the filesystem level.

**Comment by nsunami** [comment]
Thanks @chartgerink for the suggestion! I tried this with [this file](https://github.com/libscie/ResearchEquals.com/files/9839929/test-markdown.md), and I got `text/plain; charset=us-ascii`.... should this be `text/markdown` already there?

**Comment by chartgerink** [comment]
If it is the rendering would work - Uploadcare doesn't add it's own mimetype recognition it seems.

**Comment by nsunami** [comment]
I checked again on a review app, but the issue persisted on my end.

<img width="300" alt="image" src="https://user-images.githubusercontent.com/17035406/199035226-5a118489-835d-4b6d-9299-7141156defcf.png">

But, it's possible that the issue is specific to my environment.

@chartgerink Do you think it's better to close as not planned for now?

**Comment by chartgerink** [comment]
Wait was the mimetype `text/markdown`when uploading or not? If it was then this is a new bug, otherwise I guess we could close this for now as not planned?

**Comment by nsunami** [comment]
@chartgerink 

I worked on this a bit more, and I was able to render the .md file, if it is not uploaded from my computer.

### Steps that worked

1. Create a draft 
2. Add a `.md` file via URL (e.g., `https://github.com/libscie/ResearchEquals.com/files/9839929/test-markdown.md`) to uploadcare

The funny thing is that, if I download that file, and upload it again, the file will not be rendered (not recognized as a markdown file). So, as long as the file is not uploaded from my machine, it's working fine.

Overall, this issue seems to be about my local machine, not about our source code (good thing!). Thus, I'm closing this issue as not worked on. 👋
