### ISSUE TITLE
Audit the missing key props warning across the app

### ISSUE THREAD

**Issue by nsunami** [libscie/ResearchEquals.com#788]
I'm creating this issue as a parent issue to #757 to track the efforts to clean up the warning message about the missing key props.

Below are the pages to check and corresponding issues :

1. root - #757 
2. `/browse` - https://github.com/libscie/ResearchEquals.com/issues/790
3. `/graph` - Not happening ✅ 
4. `/collections` - Not happening ✅ 
5. `/dashboard` - https://github.com/libscie/ResearchEquals.com/issues/803
6. `/drafts`
7. `/invitations`
8. my modules page 
9. `SettingsModal`

**Comment by chartgerink** [comment]
Is this still relevant as it's gone stale, @nsunami?
