### ISSUE TITLE
Missing error when attempting to create collection without names in workspace

### ISSUE THREAD

**Issue by chartgerink** [libscie/ResearchEquals.com#804]
I received a DOI mint failure that I overlooked: 

```

<?xml version="1.0" encoding="UTF-8"?>
<doi_batch_diagnostic status="completed" sp="ds3.crossref.org">
   <submission_id>1544170703</submission_id>
   <batch_id>1665272237610</batch_id>
   <record_diagnostic status="Failure">
      <doi />
      <msg>Error: cvc-complex-type.2.4.b: The content of element 'person_name' is not complete. One of '{"http://www.crossref.org/schema/5.3.1":given_name, "http://www.crossref.org/schema/5.3.1":surname}' is expected.
</msg>
   </record_diagnostic>
   <batch_data>
      <record_count>1</record_count>
      <success_count>0</success_count>
      <warning_count>0</warning_count>
      <failure_count>1</failure_count>
   </batch_data>
</doi_batch_diagnostic>

```

This is because the workspace does not have a name, which I didn't think of during main feature implementation.

## Resolution

This has two pathways where this can occur - creating a collection (individual) and when making it public (collaborative and community).

Option 1: Creation/making public of a collection throws an error when the creator(s) do(es) not have their names set

This is my main proposal, and we can add other options if people have proposals :blush:

**Comment by nsunami** [comment]
@chartgerink : Option 1 sounds good to me. (Since it defers restrictions until the moment when we need it).
