### ISSUE TITLE
Describe testing strategies for dependencies in the Wiki

### ISSUE THREAD

**Issue by nsunami** [libscie/ResearchEquals.com#813]
When updating the dependabot upgrades, I feel like I'm relying on my instincts a lot (where the package is used, and what kind of package it is). I was thinking if it would be better if we can be a bit more explicit about what to test for each dependency.

Things to consider:

1. I expect that some front-end dependencies share the same testing procedure (e.g., go to the review app, and see if the page renders)
2. Other dependencies need specific commands to run (e.g., `npm run lint`, `npm run test:xml`)

Would this be helpful?

**Comment by chartgerink** [comment]
How would this be different from what is present in the wiki right now? https://github.com/libscie/ResearchEquals.com/wiki/Dependencies#major

Or do you mean specific for each package, like we also provide the descriptions?
