### ISSUE TITLE
Testing strategies for quirrel 

### ISSUE THREAD

**Issue by nsunami** [libscie/ResearchEquals.com#814]
I was working on the dependabot upgrade for quirrel (#811), and I was not 100% sure how to test.

I can access the quirrel's console via `http://localhost:9181/`. I tried clicking "invoke" on a job to clear unverified accounts, but I was unable to verify that the job worked (I was still able to log in with the unverified account).

**Comment by nsunami** [comment]
I had several instances where I was not able to use quirrel's web interface. Instead, I had to go to the API endpoints manually (e.g., `http://localhost:3000/api/weekly-digest-mailer`)

**Comment by chartgerink** [comment]
Thanks @nsunami! 

Invoking the jobs would result in console output - also if there's an error. Sometimes I add some minor logging if there's something specific I need to test.

I believe quirrel is primarily being maintained - I always double check what actually changed. Most of the time it isn't much.

Does something like this help you?

**Comment by nsunami** [comment]
Thank you for the input!  @chartgerink 

I think the best approach for testing quirrel may be:

1. invoke jobs and check conole output
2. check the test app deployment works

Would that be good for now?

**Comment by chartgerink** [comment]
Yes that works - sorry for the immense delay on this. Adding this to the wiki as well and closing this issue as it is stale :)
