### ISSUE TITLE
The quick draft modal is covered by the banner for the collections 🐛 

### ISSUE THREAD

**Issue by nsunami** [libscie/ResearchEquals.com#847]
### URL of the Page

https://www.researchequals.com/browse

### What happened?

Currently, the banner for the collection is showing up above the quick draft modal 😢 

<img width="1205" alt="image" src="https://user-images.githubusercontent.com/17035406/197165263-1f471670-b54b-4ebd-9fc1-e7ff49c60a52.png">

### Steps to reproduce

1. Go to https://www.researchequals.com/browse
2. Open the quick draft modal by pressing "+ Draft"

### What browser(s) did you use?

Chrome

### Anything else?

I think this UI bug was introduced by https://github.com/libscie/ResearchEquals.com/pull/817, when I was adjusting the z-index of the collections modal. 

I forgot to test whether the quick draft appears ok.

**Comment by chartgerink** [comment]
I think this also introduced a layering issue in the Collections modal. 

![Screenshot 2022-10-24 at 10 38 31](https://user-images.githubusercontent.com/2946344/197484439-d1d67920-e810-4d2d-8c62-7a1f25c436f5.png)

These are the kinds of bugs we have to learn from and understand why they're happening so we prevent them in the future. It would be good if we check all the instances where #817 made changes.
