### ISSUE TITLE
Porting a new marketing page ⭐ 

### ISSUE THREAD

**Issue by nsunami** [libscie/ResearchEquals.com#867]
We have a new design for the marketing page (available in [this GitHub Repo](https://github.com/Apollo-11-Digital-Lab-Co/research-equals-ui)), and it's time to port that here!

We want to:
1.  Port the main content
2. Port the footer into the root `/` without replacing the footer component 
3. Port the banner as a component

We are not porting the nav bar.

Edit: Updated to reflect the comment by @chartgerink 🙌

**Comment by chartgerink** [comment]
Ah sorry if I didn't communicate clearly earlier - I meant to say to port the footer into the `/` but not to replace the footer component as it's used throughout the app! 😅

**Comment by nsunami** [comment]
I see! thanks for clarifying, Chris!
