### ISSUE TITLE
Next module icon overflowing into the scroll bar when opening a slide out 🐛 

### ISSUE THREAD

**Issue by nsunami** [libscie/ResearchEquals.com#889]
### URL of the Page

https://www.researchequals.com/modules/nf48-5kcp

### What happened?

This is a small visual bug, I noticed that when I open a slide-out, the next-module icon (+) overflows out to the right, into the scroll bar

![image](https://user-images.githubusercontent.com/17035406/199512284-eea3ae27-b620-4c7d-b785-fa582c4dd3dd.png)

### Steps to reproduce

1. On mac, connect an external mouse
2. Got to a module that has a parent (e.g., https://www.researchequals.com/modules/nf48-5kcp)
3. Click the previous module icon to open the slide out (<-)

Note: This issue does not happen when I disconnect an external mouse from my Mac, since doing so will hide the scrollbar on browser. 

### What browser(s) did you use?

Chrome

### Anything else?

Reproduced on Chrome, Firefox, and Sarafi!

It's a small bug, but it would be nice if the icon does not move---it's a bit of uneasy feeling 😆

**Comment by chartgerink** [comment]
Closing this as it won't be worked on right now. If you still want it fixed @nsunami of course you're allowed to work on it anytime 😊
