### ISSUE TITLE
Placing the collections icon on top of the title, instead to the left?

### ISSUE THREAD

**Issue by nsunami** [libscie/ResearchEquals.com#895]
Currently, the icon for the collections is shown on the left of the page:

<img width="1056" alt="image" src="https://user-images.githubusercontent.com/17035406/199681073-19f467c1-99db-4a9c-b8a1-c2e2c9cce7ca.png">

<img width="475" alt="image" src="https://user-images.githubusercontent.com/17035406/199681274-8afb2dca-b2c0-453d-b538-b2b931435151.png">

The icon may be better placed on top of the title.

Let's experiment on this to see how it looks like 💡

**Comment by chartgerink** [comment]
Leaving as-is for now.
