### ISSUE TITLE
Chat icon and the snack bar/toast are overlapping 🐛 

### ISSUE THREAD

**Issue by nsunami** [libscie/ResearchEquals.com#897]
### URL of the Page

collections admin page

### What happened?

In a mobile view, the snack bar and the chat icon overlap with each other:

![image](https://user-images.githubusercontent.com/17035406/199684105-146e97a8-01d8-4f15-aa1f-f9cf2ed7ce77.png)

We may want to consider showing the snack bar on top of the chat icon. 

### Steps to reproduce

Example:
1. Go to one's individual collection
2. Try changing the role to another role 
3. The toast snack bar appears on the bottom 

### What browser(s) did you use?

Chrome

### Anything else?

We identified this item during our work on collections quality assurance

**Comment by chartgerink** [comment]
Hahaha I like the terminology `snack bar` - it's called a toast by the developers 🍞 

![](https://media.giphy.com/media/QFg4iwkM7ZJnO/giphy.gif?cid=ecf05e476y0e2i6ztcbbrxyk2uw7zuq36fa4vox3m36z3bib&rid=giphy.gif&ct=g)

**Comment by chartgerink** [comment]
This would require us to dig a bit into the SDK for crisp - which I would prefer to do in a bigger effort as we improve customer support in the future.

Wontfix for now.
