### ISSUE TITLE
Asking users to add an alt description for the main image file 

### ISSUE THREAD

**Issue by nsunami** [libscie/ResearchEquals.com#901]
When working on https://github.com/libscie/ResearchEquals.com/pull/793#pullrequestreview-1169961825, we identified that it would be important to add the alt description for the main image file for users with screen readers.

We want to think about a way to ask alt descriptions when uploading an image as the main file.

**Comment by chartgerink** [comment]
I am adding this to the backlog as this isn't planned right now.
