### ISSUE TITLE
Tracing the tree for better DX 🌳 

### ISSUE THREAD

**Issue by nsunami** [libscie/ResearchEquals.com#928]
As our code base gets bigger, we face challenges of maintaining all files. To optimize our codebase and DX, we want to examine our codebase systematically to identify the areas of improvement.

I'm creating this issue to track our efforts for going through directories and get a good picture of our codebase tree 🌳 .

I plan to create a new issue for each specific improvement I identify via this effort, and add it to this issue.

**Comment by chartgerink** [comment]
Thanks Nami! We have everything documented in Notion, so I'll close this for now.
