### ISSUE TITLE
Simplifying the form validation in the profile setting

### ISSUE THREAD

**Issue by nsunami** [libscie/ResearchEquals.com#977]
While working on #976, I noticed that the form validation in the profile setting could be simplified, and thus we could possibly improve the code readability there.

I think this is a low-priority issue, but I don't want to lose it. So, I'm creating an issue and a corresponding branch. 👍

**Comment by chartgerink** [comment]
Could you specify what could be simplified? That would be helpful if I wanted to take a looksie or assess whether it is necessarily complicated :-)

**Comment by chartgerink** [comment]
Closing this as a more considerable rework of the settings is necessary, #1071 as a quick fix caused unnecessary hangs on the application in the input fields.
