### ISSUE TITLE
Module does not resolve

### ISSUE THREAD

**Issue by psobrakseaton** [libscie/ResearchEquals.com#98]
Browser: Safari

When I browse to a published module, I get an error reading:
> “400 null is not an object (evaluating 'l.name').”

<img width="1370" alt="Screen Shot 2021-11-29 at 10 24 01" src="https://user-images.githubusercontent.com/28573875/143841430-80b44445-b155-483b-84ad-a3c506679410.png">
<img width="616" alt="Screen Shot 2021-11-29 at 10 26 48" src="https://user-images.githubusercontent.com/28573875/143841827-9204adbc-4359-4394-99de-156a1b038cac.png">

**Comment by chartgerink** [comment]
Ah yes - this is an error that is caused by not having adequate checks before approving to publish!

You should only be able to approve to publish when:

* You connected your ORCID
* You added your name
* Your email is verified

These few limitations are not checked as of yet. Will improve!
