### ISSUE TITLE
“Follow” button remains after following

### ISSUE THREAD

**Issue by chartgerink** [libscie/ResearchEquals.com#99]
When visiting a profile, I follow them successfully, but the ‘Follow’ button remains. I would expect this to either turn to ‘Unfollow’ (or something akin to it) or go away completely.

## Screenshot(s)

![Screenshot 2021-11-29 at 09 50 41](https://user-images.githubusercontent.com/2946344/143841453-aea80057-8a5d-437e-b918-fa12da219400.png)

**Comment by mkim219** [comment]
Hi @chartgerink, I would like to work on this issue. Can you assign me?

**Comment by chartgerink** [comment]
Hi @mkim219 - I haven't seen you around before. Welcome!

Please feel invited to make pull requests - things are in active development and moving rather quickly. Assigning the issue is not an option at this point, as a result.

**Comment by chartgerink** [comment]
#107 already fixes this issue - as I mentioned, things can move rather quickly 😅 Please do feel invited to make PRs for any other outstanding issue if you feel like doing so 👍
